# 本地开发配置文件（优先级高于Nacos配置）
# 如果需要本地单独配置SQL日志，可以在此文件配置

logging:
  level:
    # MyBatis-Plus SQL日志打印配置
    com.cloud.admin.mapper: DEBUG
    # MyBatis SQL日志打印
    org.apache.ibatis: DEBUG
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: DEBUG
    java.sql.ResultSet: DEBUG
    # 如果使用logback，可以设置根日志级别
    root: INFO


